# Generated by Django 4.2.6 on 2023-10-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopapp', '0002_frame_description_alter_frame_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
