# Generated by Django 4.2.6 on 2023-11-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshopapp', '0007_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='image_url',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
